# Generated by Django 4.1.12 on 2023-11-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="type",
        ),
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("follow", "Follow"),
                    ("appointment", "Appointment"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PostNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_id", models.PositiveBigIntegerField()),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.notification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followed_id", models.PositiveBigIntegerField()),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.notification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointmentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_id", models.PositiveBigIntegerField()),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.notification",
                    ),
                ),
            ],
        ),
    ]
