# Generated by Django 4.2.6 on 2023-11-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_is_staff_useraccount_is_doctor_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
